###  Auth Requests
POST http://localhost:3005/api/auth/signup
Content-Type: application/json

{
    "username" : "newUser",
    "password" : "denuke2",
    "email" : "new@gmail.com"
}

###
POST http://localhost:3005/api/auth/login
Content-Type: application/json

{
    "username" : "denukedd19997",
    "password" : "denuke2",
    "email" : "denukedd97@gmail.com"
}

###
GET http://localhost:3005/api/auth/login/success



####  User Requests
GET http://localhost:3005/api/user?latest=true

### 
GET http://localhost:3005/api/user/624a0a28945987d3fb86c9dd

###
PUT http://localhost:3005/api/user/624a0a28945987d3fb86c9dd
Content-Type: application/json

{
    "password" : "denukedissa"
}

###
DELETE http://localhost:3005/api/user/6251a4c1a7078005027f402c

### 
GET http://localhost:3005/api/user/stats


### Product Reqests
POST http://localhost:3005/api/product
Content-Type: application/json

{
    "name" : "Dress",
    "description" : "Dress for wemen",
    "image" : "https://www.collinsdictionary.com/images/full/dress_31690953_1000.jpg",
    "price" : "14.19"
}

###
GET http://localhost:3005/api/product

###
GET http://localhost:3005/api/product?latest=true

###
GET http://localhost:3005/api/product?category=men

###
GET http://localhost:3005/api/product/6251dbe86d302ecd21d7bd40

###
DELETE http://localhost:3005/api/product/6251dbe86d302ecd21d7bd40

###

PUT http://localhost:3005/api/product/6251db9d49afddb7eb398fc7
Content-Type: application/json

{
    "categories" : ["shirt", "men", "cashual"]
}




### Cart Reqests
POST http://localhost:3005/api/cart
Content-Type: application/json

{
   "userID": "624a0a28945987d3fb86c9dd",
    "products": [
        { "productId": "6251daf4b14a15a2afa9eac8" , "quantity": 1 },
        { "productId": "6251daf4b14a15a2afa9eac8" , "quantity": 2 }
    ]
}

###
GET http://localhost:3005/api/cart

###
GET http://localhost:3005/api/cart/6251fa43e99229d1782ffddb

###
DELETE http://localhost:3005/api/cart/6251fa43e99229d1782ffddb

###

PUT http://localhost:3005/api/cart/6251fa51e99229d1782ffddf
Content-Type: application/json

{
   "userID": "624df60b0ab3ada14ece5451",
    "products": [
        { "productId": "6251daf4b14a15a2afa9eac8" , "quantity": 9 },
        { "productId": "6251db9d49afddb7eb398fc7" , "quantity": 5 }
    ]
}